### ISSUE TITLE
Using concealwallet RPC, I can send a comment for free

### ISSUE THREAD

**Issue by lumenano** [TheCircleFoundation/conceal-cli#7]
My understanding is that there now a fee for comments attached to payments, equal to 10 X per character, in addition to the base fee of 10 X for a payment.

![tx](https://user-images.githubusercontent.com/37015389/41992116-4120ff8a-7a50-11e8-8a44-975ef53b26d4.jpg)

**Comment by krypt0x** [comment]
hi, we are analising it and will get back to you soon. thanks

**Comment by lumenano** [comment]
According to krypt0x, this is now a feature of the CLI wallet, not a bug.
