### ISSUE TITLE
simplewallet does not produce deterministic wallets

### ISSUE THREAD

**Issue by cryptokatz** [TheCircleFoundation/conceal-cli#8]
I added support for 25 word mnemonic seeds to an internal test build of the Conceal CLI. However, during the process, I realized that the Conceal simple wallet is not deterministic.

Most coins with newer codebases use deterministic key derivation to derive the view key from the spend key. Since the mnemonic seed is a representation of the spend key, you could use one or the other to generate all the other keys.

The Conceal simple wallet uses an older method of randomly generating the view key. The problem with this approach is that in order to restore a wallet, a user will need to use both the spend key and the view key, rather than simply the spend key or the mnemonic seed. Also, since the private key and public key pairs are part of the address creation process, the wallet address will also be different.

Note that the paper wallet generator does create deterministic spend keys, and is not affected by this issue. 

Who is affected?
Anyone who created a wallet using simple wallet. These users will not be able to generate mnemonic seeds for their wallets.

The solution:

1. add support for deterministic key derivation 
2. display the mnemonic seeds only if the view key can be derived from the spend key
3. display the mnemonic seeds for new wallets

I will start working on the solution.

**Comment by cryptokatz** [comment]
The changes are complete, and I am running multiple rounds of testing to ensure that the behavior matches the following:

1. export_keys only shows the spend and view keys when the wallet was created before the upgrade
2. export_keys provide the mnemonic seed in addition to the keys for wallets created after the upgrade
3. new wallet creation shows the seed in addition to the keys
4. import wallet using keys created before the upgrade
5. import wallet using keys created after the upgrade
6. import wallet using mnemonic seed from the paper wallet
7. import wallet using mnemonic seed 

I expect to push the changes to master sometime in the next couple of days

**Comment by krypt0x** [comment]
great job katz

**Comment by cryptokatz** [comment]
This is complete
